[firstbt]
devfile = "/dev/rfcomm0"
baud = 9600
  [[firstbt.adcs]]
  id = "A1"
  cmdget = "A1"
  vref = 4.5
  expr = "adcval * (vref / 256)"
  [[firstbt.adcs]]
  id = "A2"
  cmdget = "A2"
  vref = 4.5
  expr = "adcval * (vref / 256)"
  [[firstbt.adcs]]
  id = "A2"
  cmdget = "A2"
  vref = 4.5
  expr = "adcval * (vref / 256)"
  [[firstbt.tmpts]]
  id = "T1"
  cmdlsb = "L1"
  cmdmsb = "M1"
  [[firstbt.tmpts]]
  id = "T2"
  cmdlsb = "L2"
  cmdmsb = "M2"
  [[firstbt.swts]]
  id = "SW1"
  cmdget = "G1"
  cmdset = "S1"
  cmdclr = "C1"
